### PR TITLE
 rearrange design docs 

### LINKED ISSUE #80: Folder and file organization for old files
Folder and file organization for old files
architecture-analysis
>>>Analysis
>>>arch-design
>>>>>old-archive
>>>>>soda-overall
>>>>> <Project specific folder>
>>>>>>>>>Project related design/arch docs

### PR DESCRIPTION
**Pull request by kumarashit**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
/kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**What this PR does / why we need it**:
Rearrange design docs into the specific project folder or location and archiving older specs like that of telemetry

**Which issue(s) this PR fixes**:

Fixes #80 

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
/kind NOT-TESTED

**Test Report**:
N/A

**Special notes for your reviewer**:

### CODE REVIEW

**Review by skdwriting — COMMENTED** [review]
@kumarashit can you please check whether it is updated as per the changes in the repo name and folder. Need a rebase? Please check and confirm

**Comment by kumarashit** [comment]
> @kumarashit can you please check whether it is updated as per the changes in the repo name and folder. Need a rebase? Please check and confirm

Done. Please check now. Thanks

**Review by skdwriting — APPROVED** [review]
LGTM
please resolve conflict

**Review by NajmudheenCT — APPROVED** [review]
LGTM

**Pull request merged**
